export const allProjects = [
  {
    title: "Project Alpha",
    tag: "Full Stack",
    stack: ["React", "Node.js", "MongoDB"],
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    github: "#",
    demo: "#",
    color: "#a78bfa",
    year: "2024",
  },
  {
    title: "Project Beta",
    tag: "Frontend",
    stack: ["Next.js", "TypeScript", "Tailwind"],
    desc: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute.",
    github: "#",
    demo: "#",
    color: "#60a5fa",
    year: "2024",
  },
  {
    title: "Project Gamma",
    tag: "Backend",
    stack: ["Express", "PostgreSQL", "Redis"],
    desc: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint.",
    github: "#",
    demo: "#",
    color: "#f472b6",
    year: "2023",
  },
  {
    title: "Project Delta",
    tag: "Mobile",
    stack: ["React Native", "Firebase", "Expo"],
    desc: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum lorem.",
    github: "#",
    demo: "#",
    color: "#34d399",
    year: "2023",
  },
  {
    title: "Project Epsilon",
    tag: "Full Stack",
    stack: ["React", "Django", "PostgreSQL"],
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
    github: "#",
    demo: "#",
    color: "#a78bfa",
    year: "2024",
  },
  {
    title: "Project Zeta",
    tag: "Frontend",
    stack: ["Vue.js", "Pinia", "Vite"],
    desc: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    github: "#",
    demo: "#",
    color: "#60a5fa",
    year: "2023",
  },
  {
    title: "Project Eta",
    tag: "Backend",
    stack: ["Go", "gRPC", "Redis"],
    desc: "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum.",
    github: "#",
    demo: "#",
    color: "#f472b6",
    year: "2023",
  },
  {
    title: "Project Theta",
    tag: "Mobile",
    stack: ["Flutter", "Firebase", "Dart"],
    desc: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem.",
    github: "#",
    demo: "#",
    color: "#34d399",
    year: "2022",
  },
  {
    title: "Project Iota",
    tag: "DevOps",
    stack: ["Docker", "Kubernetes", "AWS"],
    desc: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit sed quia consequuntur magni.",
    github: "#",
    demo: "#",
    color: "#fbbf24",
    year: "2022",
  },
  {
    title: "Project Kappa",
    tag: "AI/ML",
    stack: ["Python", "TensorFlow", "FastAPI"],
    desc: "Ut labore et dolore magnam aliquam quaerat voluptatem ut enim ad minima veniam quis nostrum exercitationem.",
    github: "#",
    demo: "#",
    color: "#f87171",
    year: "2022",
  },
];

// First 4 shown on main timeline
export const featuredProjects = allProjects.slice(0, 4);
