export const allProjects = [
    {
    title: "Interview Master",
    tag: "AI + Full Stack",
    stack: ["MongoDB", "Express.js", "React", "Node.js", "GenAI"],
    desc: "Interview Master is an AI-powered interview preparation platform built using the MERN stack. It helps users practice interviews with intelligent question generation, personalized feedback, and real-time evaluation using Generative AI.",
    github: "https://github.com/ankurgandhi8789/interview-master",
    // demo: "#",
    color: "#a78bfa",
    year: "2026",
    },
  {
  title: "Thakur Shop Complaint Portal",
  tag: "Full Stack MERN Project",
  stack: ["MongoDB", "Express.js", "React.js", "Node.js"],
  desc: "A complaint portal developed for electric and electronics shops where customers can submit complaints by filling in their details and issue information. Mechanics receive the complaint, visit the customer’s location, and solve the problem efficiently through the platform.",
  github: "https://github.com/ankurgandhi8789/ThakurShopFrontend",
  demo: "https://thakur-shop.vercel.app/",
  color: "#34d399",
  year: "2024",
},
{
  title: "AI Consultancy Chatbot",
  tag: "GenAI Project",
  stack: ["GenAI", "React.js"],
  desc: "An AI-powered chatbot developed for MS Consultancy Services to communicate with clients and answer their queries efficiently. The chatbot provides quick responses, improves client interaction, and helps users get consultancy-related information in an easy and interactive way.",
  github: "https://github.com/ankurgandhi8789/ask-question-client",
  demo: "https://ask-question-client.vercel.app/",
  color: "#60a5fa",
  year: "2025",
},
  {
    title: "Employee Task Management System",
    tag: "Full Stack",
    stack: ["MongoDB", "Express", "React", "Node.js"],
    desc: "A full-stack employee task management system where admins can assign tasks to employees and manage their workflow. It includes features like task status tracking (pending, completed, rejected), employee management (add/remove employees), and a user-friendly interface for employees to view and update their tasks.",
    github: "https://github.com/ankurgandhi8789/employee_management",
    // demo: "#",
    color: "#f472b6",
    year: "2025",
  },
  {
    title: "Personal Portfolio Website",
    tag: "Frontend",
    stack: ["React"],
    desc: "A personal portfolio website built using React to showcase my projects, skills, and experience. It features a responsive design, smooth navigation, and interactive UI components to provide a seamless user experience.",
    github: "https://github.com/ankurgandhi8789/ankur-portfolio",
    demo: "https://ankur-portfolio-lake.vercel.app/",
    color: "#34d399",
    year: "2026",
  },
  {
  title: "React Router Project",
  tag: "Frontend",
  stack: ["React", "React Router"],
  desc: "A React-based project demonstrating client-side routing using React Router. It includes multiple pages, dynamic navigation, and seamless transitions without page reloads, showcasing the fundamentals of single-page application (SPA) development.",
  github: "https://github.com/ankurgandhi8789/ReactRouterProject",
  // demo: "#",
  color: "#60a5fa",
  year: "2024",
},
  {
    title: "E-Waste Management System",
    tag: "Frontend Project",
    stack: ["HTML", "CSS", "JavaScript"],
    desc: "An E-Waste Management System developed as my first project during 2nd year. It focuses on spreading awareness about proper disposal of electronic waste and provides a simple interface for users to understand recycling methods and environmental impact.",
    github: "https://github.com/ankurgandhi8789/e-waste-management",
    demo: "https://ankurgandhi8789.github.io/Waste-Management/",
    color: "#34d399",
    year: "2024",
  },
];

// First 4 shown on main timeline
export const featuredProjects = allProjects.slice(0, 4);
